### ISSUE TITLE
Streams Support

### ISSUE THREAD

**Issue by hitchcott** [hex7c0/mongodb-restore#1]
Similar to: https://github.com/hex7c0/mongodb-backup/issues/1

I'm hoping to implement a fully streaming backup/restore. I managed to get the backup working successfully using your latest update (which currently isn't published to NPM?), but now I'd like to do the same for the restore; to accept a stream from an POST file upload directly.

Thanks for the package!

**Comment by hex7c0** [comment]
hi hitchcott
thanks for the feedback
I'm working on it (main it's ready, I'm writing testing code)

**Comment by hitchcott** [comment]
Thanks for the quick update! It's working great for me. :dancers: 

Quick question. Do you support something similar to the `mongorestore --drop` option?

**Comment by hex7c0** [comment]
no problem :)
next commit
