### ISSUE TITLE
An error, probably something to do with callbacks and error handling

### ISSUE THREAD

**Issue by axelpale** [hex7c0/mongodb-restore#10]
When I run my code:

```
...
var root = path.resolve(local.mongo.backupDir, dirname);

restore({
  uri: local.mongo.url,
  root: root,
  dropCollections: true,
  callback: function (err) {
    if (err) {
      return cb(err);
    }  // else

    return cb(null, dirname);
  },
});
```

and when `cb` is a function defined above, then I get this:

```
/Users/xeli/Build/tresdb/node_modules/mongodb/lib/utils.js:98
process.nextTick(function() { throw err; });
                              ^

TypeError: Cannot read property 'message' of null
    at error (/Users/xeli/Build/tresdb/node_modules/mongodb-restore/index.min.js:4:15)
    at /Users/xeli/Build/tresdb/node_modules/mongodb-restore/index.min.js:78:90
    at Array.forEach (native)
    at fromBson (/Users/xeli/Build/tresdb/node_modules/mongodb-restore/index.min.js:76:46)
    at /Users/xeli/Build/tresdb/node_modules/mongodb-restore/index.min.js:104:17
    at meta (/Users/xeli/Build/tresdb/node_modules/mongodb-restore/index.min.js:178:16)
    at /Users/xeli/Build/tresdb/node_modules/mongodb-restore/index.min.js:103:18
    at handleCallback (/Users/xeli/Build/tresdb/node_modules/mongodb/lib/utils.js:96:12)
    at /Users/xeli/Build/tresdb/node_modules/mongodb/lib/db.js:531:9
    at handleCallback (/Users/xeli/Build/tresdb/node_modules/mongodb/lib/utils.js:96:12)
```

Next I looked into `mongodb/lib/utils.js:96` and `mongodb-restore/index.min.js:103`. The issue seems to relate to callbacks and error handling. Lines 3–5 in `mongodb-restore/index.min.js:` has the following:

```
function error(err) {
    logger(err.message);
}
```

Therefore `TypeError: Cannot read property 'message' of null` comes from this function. Thus it seems that `err` is null. I also tried to run `restore` **without** following lines:

```
dropCollections: true,
  callback: function (err) {
    if (err) {
      return cb(err);
    }  // else

    return cb(null, dirname);
  },
```

But it resulted with the same error. The previous mongodb-restore commits have had some to do with callbacks and error handling, including:
- https://github.com/hex7c0/mongodb-restore/commit/2c51a7d20bce197a0ddac91d99784e6fefc86948
- https://github.com/hex7c0/mongodb-restore/commit/4e13b74dec75fc03327b77be76aec6e71639c5bb
- https://github.com/hex7c0/mongodb-restore/commit/a564a4da5605f91f6841e83f097e51c7a7c0effe

**Comment by axelpale** [comment]
I am using:
- mongodb 2.2.10
- mongodb-restore 1.5.6

**Comment by axelpale** [comment]
The error vanished after postfixing the root path with the database name.

```
root: path.resolve(root, 'mydatabasename'),
```

Thus, the error was primarily caused by wrong root path.

I propose at least some of the following to be done to prevent similar issues with future users:
- let us **improve root option documentation**. Its definition is too easily messed up with the same option of mongodb-backup that does not require the database name.
- in API docs, replace the line `root: __dirname + '/db'` with a more self-explanatory line like `root: __dirname + '/dbname`. At least for me, `'/db'` was just **too generic** to inform about that a database name is meant instead of just an arbitrarily named db backup directory.
- **improve the error handling** so that it becomes clear that `root` is bad and does not point to a  database directory under the backup root dir.
- parse the database name from the `uri` option where it is also required and append the name to root. However, this is not backwards compatible.

Let me know if help in improving the documentation is needed.

**Comment by hex7c0** [comment]
thanks for your feedback!
a PR for improve documentation is welcome

**Comment by axelpale** [comment]
Thanks for the patch! I believe you just saved many users from moments of despair. Great :)
