### ISSUE TITLE
2dsphere index becomes corrupted during restore

### ISSUE THREAD

**Issue by axelpale** [hex7c0/mongodb-restore#12]
Here are the indices before backup:

```
> db.locations.getIndexes()
[
    {
        "v" : 1,
        "key" : {
            "_id" : 1
        },
        "name" : "_id_",
        "ns" : "tresdb.locations"
    },
    {
        "v" : 1,
        "key" : {
            "geom" : "2dsphere"
        },
        "name" : "geom_2dsphere",
        "ns" : "tresdb.locations",
        "2dsphereIndexVersion" : 3
    }
]
```

And here are the indices after restore:

```
> db.locations.getIndexes()
[
    {
        "v" : 1,
        "key" : {
            "_id" : 1
        },
        "name" : "_id_",
        "ns" : "tresdb.locations"
    },
    {
       "v" : 1,
       "key" : {
            "geom_2dsphe" : 1
        },
        "name" : "geom_2dsphere",
        "ns" : "tresdb.locations",
        "2dsphereIndexVersion" : 3
    }
]
```

Thus, the geospatial index becomes corrupted. After restore, my geospatial queries fail because missing geospatial index.

I believe the bug lies in these functions:
- [mongodb-backup/index.js/writeMetadata](https://github.com/hex7c0/mongodb-backup/blob/1.6/index.js#L36)
- [mongodb-restore/index.js/readMetadata](https://github.com/hex7c0/mongodb-restore/blob/1.5/index.js#L36)

Because of this bug, **mongodb-backup** and **mongodb-restore** are not applicable when working with geospatial data.

**Comment by hex7c0** [comment]
thanks for your feedback!

**Comment by axelpale** [comment]
Thanks for the fix! So cool, I will try it out soon :)
