### ISSUE TITLE
Mongodb-Restore throws the error: missing root option  on centos7 platform

### ISSUE THREAD

**Issue by zqr688** [hex7c0/mongodb-restore#9]
# Hi ,The error  information:

> **error: [restoreDump] Error: missing root option
>         at restore (/opt/tests/bundle/programs/server/npm/npm-container/node_modules/mongodb-restore/index.min.js:212:30)
>         at [object Object].Meteor.methods.restoreDump (server/mongodb/methods_dump_restore.js:14:1)
>         at maybeAuditArgumentChecks (livedata_server.js:1698:12)
>         at livedata_server.js:708:19
>         at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
>         at livedata_server.js:706:40
>         at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
>         at livedata_server.js:704:46
>         at tryCallTwo (/opt/tests/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
>       at doResolve (/opt/tests/bundle/programs/server/npm/promise/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)**

**Is it a bug? And how to deal with it**

**Comment by hex7c0** [comment]
https://github.com/rsercano/mongoclient/issues/131
https://github.com/rsercano/mongoclient/pull/166
